layout_spectrum: 0.9091169405728579
typography_spectrum: 0.8382978
name: TastyBitz
title: 'Lose your mind and come to your senses!'
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.15441971295513213
  saturation: 0.18754216167144477
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  lightness: 0.4236960706766695
  rhythmicContrast: 0.2918015862815082
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/18222de8-7e49-4400-af3d-190e03fb37c0.png'
